module KN1DJl

using JSON
using Interpolations
using Unitful
using Dierckx
using NPZ
using LinearAlgebra

include("constants.jl")
include("utils.jl")
include("make_dvr_dvx.jl")
include("create_shifted_maxwellian.jl")
include("kinetic_mesh.jl")
include("interp_fvrxx.jl")
include("rates/janev/_helpers.jl")
include("rates/janev/sigma_cx_h0.jl")
include("rates/janev/sigma_cx_hh.jl")
include("rates/janev/sigma_el_h_h.jl")
include("rates/janev/sigma_el_h_hh.jl")
include("rates/janev/sigma_el_hh_hh.jl")
include("rates/janev/sigma_el_p_h.jl")
include("rates/janev/sigma_el_p_hh.jl")
include("rates/janev/sigmav_cx_h0.jl")
include("rates/janev/sigmav_cx_hh.jl")
include("rates/janev/sigmav_h1s_h1s_hh.jl")
include("rates/janev/sigmav_h1s_h2s_hh.jl")
include("rates/janev/sigmav_h1s_hn3_hh.jl")
include("rates/janev/sigmav_h1s_hn_hp.jl")
include("rates/janev/sigmav_h2p_h2s_hh.jl")
include("rates/janev/sigmav_ion_h0.jl")
include("rates/janev/sigmav_ion_hh.jl")
include("rates/janev/sigmav_p_h1s_hh.jl")
include("rates/janev/sigmav_p_h1s_hp.jl")
include("rates/janev/sigmav_p_hn2_hp.jl")
include("rates/janev/sigmav_p_p_hp.jl")
include("rates/janev/sigmav_rec_h1s.jl")
include("rates/Johnson_Hinnov/johnson_hinnov.jl")
include("rates/adas/adas_ionisaation.jl")
include("rates/collrad/collrad_sigmav_ion_h0.jl")
include("kinetic_h.jl")
include("kinetic_h2.jl")
include("kn1d.jl")
include("kn1d_lite.jl")

export KineticHConfig,
       KineticH2Config,
       CollisionConfig,
       KN1DConfig,
       KN1DLinearInterp1D,
       KN1DLiteOutput,
       VSpaceDifferentials,
       get_local_directory,
       get_json,
       get_config,
       debrief,
       sval,
       poly,
       linear_interp_1d,
       interp_1d,
       evaluate!,
       path_interp_2d,
       bs2dr,
       reverse_dim,
       kn1d_lite_output_placeholder,
       kn1d_output_placeholders,
       INTERPOLATION_ENTRY_POINTS,
       KN1D_LITE_OUTPUT_KEYS,
       KN1D_OUTPUT_FILES,
       KN1D_OUTPUT_SCHEMA,
       DEFAULT_CONFIG_PATH,
       sigma_cx_h0,
       sigma_cx_hh,
       sigma_el_h_h,
       sigma_el_h_hh,
       sigma_el_hh_hh,
       sigma_el_p_h,
       sigma_el_p_hh,
       sigmav_cx_h0,
       sigmav_cx_hh,
       sigmav_h1s_h1s_hh,
       sigmav_h1s_h2s_hh,
       sigmav_h1s_hn3_hh,
       sigmav_h1s_hn_hp,
       sigmav_h2p_h2s_hh,
       sigmav_ion_h0,
       sigmav_ion_hh,
       sigmav_p_h1s_hh,
       sigmav_p_h1s_hp,
       sigmav_p_hn2_hp,
       sigmav_p_p_hp,
       sigmav_rec_h1s,
       JohnsonHinnov,
       jhr_spline,
       jhr_coef,
       jhs_coef,
       jhalpha_coef,
       bs2dr_jh,
       nh_saha,
       lyman_alpha,
       balmer_alpha,
       read_adf11,
       ADF11Interpolator,
       make_adf11_interpolator,
       scd_adas,
       acd_adas,
       collrad_sigmav_ion_h0,
       KHCollisions,
       MeshEqCoefficients,
       CollisionType,
       KHResults,
       KineticHOutput,
       KineticHErrors,
       KineticHInput,
       KineticHInternal,
       KineticHH2Moments,
       KineticH,
       KH2Collisions,
       KH2MeshEqCoefficients,
       KH2CollisionType,
       KH2Results,
       KineticH2Output,
       KineticH2Errors,
       KineticH2Input,
       KineticH2Internal,
       KineticH2HMoments,
       KineticH2,
       run_procedure,
       KN1DResults,
       kn1d,
       KN1DLiteResults,
       KN1DLiteProblem,
       default_johnson_hinnov,
       prepare_kn1d_lite,
       run_kn1d_lite,
       kn1d_lite,
       compensate_distribution,
       create_shifted_maxwellian,
       interp_fvrxx,
       KineticMesh,
       create_vr_vx_mesh,
       return_mesh_info

end
